version: '3.8'

services:
  producer:
    build: .
    environment:
      KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:9092
    command: ["python", "src/data_producer.py"]

  consumer:
    build: .
    environment:
      KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:9092
    depends_on:
      - producer
    command: ["python", "src/data_consumer.py"]